export { Summoner as Summoner } from './summoner.interface'
export { Rank as Rank } from './player.interface'
export { Champ as Champ } from './player.interface'
export { Mastery as Mastery } from './player.interface'
export { Player as Player } from './player.interface'
