export { default as getIndexOfString } from './getIndexOfString'
export { default as getStatValues } from './getStatValues'
export { default as processData } from './processData'
export { default as realName } from './realName'
export { default as trophyIcon } from './trophyIcon'
export { default as statTitle } from './statTitle'