export { RiotChampions as RiotChampionsDto } from './riotChampions.dto'
export { RiotGame as RiotGameDto } from './riotGame.dto'
export { RiotMastery as RiotMasteryDto } from './riotMastery.dto'
export { RiotRank as RiotRankDto } from './riotRank.dto'
export { RiotSummoner as RiotSummonerDto } from './riotSummoner.dto'
