export { RiotAugment as RiotAugmentDto } from './riotAugment.dto'
export { RiotChampions as RiotChampionsDto } from './riotChampions.dto'
export { RiotGame as RiotGameDto } from './riotGame.dto'
export { RiotRank as RiotRankDto } from './riotRank.dto'
export { RiotSummoner as RiotSummonerDto } from './riotSummoner.dto'
